### ISSUE TITLE
editor crashes when markdown with raw <iframe> in document

### ISSUE THREAD

**Issue by jdonaldson** [jmbuhr/otter.nvim#193] opened 2024-12-17 20:46 UTC
I'm using otter through quarto, whenever I accidentally insert a "raw" <iframe> tag into the content it breaks the editor.  I can't save the content, or change it back using vim.  To fix it I had to manually save the raw iframe in an html literal :

```

```{=html}
<iframe src="src" width="100%" height="400"></iframe>
```

I'm guessing otter is throwing an error when it hits a raw iframe.  I think the principle of least surprise would be to ignore it, but there may be something more clever.

**Comment by jmbuhr** [comment] 2024-12-17 22:02
What hints at otter as being responsible for the crash?

**Comment by jmbuhr** [comment] 2024-12-17 22:10
Note, that until I have finished a custom treesitter grammar extension for quarto and pandoc, quarto is just using the regular markdown grammar. This is relevant here because in this grammar, `=html` is not recognized as `html`. This in turn means there can't be an html treesitter injection in this example, which means that otter will not pick it up. Ergo otter can't crash here.

**Comment by jdonaldson** [comment] 2024-12-19 01:08
> What hints at otter as being responsible for the crash?

Good question, and in fact the crash is not happening after I updated.  The issue now is that I can't save a file that has a raw <iframe>...</iframe> content in a qmd file.  Or rather, if I open one with a raw <iframe> in it, I can't save any changes.  It says a file already exists with that name.

If I disable otter (and nothing else), it goes away.

**Comment by jmbuhr** [comment] 2024-12-19 10:28
I can't reproduce that.
![image](https://github.com/user-attachments/assets/727b68c9-b2ca-46f0-865a-fbdad9dd7a3b)
![image](https://github.com/user-attachments/assets/6bf369cc-8d08-4169-b89e-97d96d650d55)
No crashes.

**Comment by jmbuhr** [comment] 2024-12-19 10:30
Let me know when you have a minimal reproducible example, then I'm happy to help. Closing for now.

**Closed by jmbuhr** 2024-12-19 10:30 UTC
